services:
  mongo:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:4000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=${MONGO_PORT}
      - MONGODB_URI=mongodb://${MONGODB_HOST}:${MONGO_PORT}/your_database
      - NODE_ENV=development
    dns:
      - 8.8.8.8
      - 8.8.4.4
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
volumes:
  mongo-data: